.PHONY: all build clean deploy purge

all: ../dist/gh-pages/spEnergiesQD/Manuscript/paper.pdf ../dist/gh-pages/spEnergiesQD/figures.pdf

clean:
	for dir in . Manuscript; do ( cd $${dir} && rm -fr *.aux *.bbl *.blg *.dep *.fdb_latexmk *.fls *.log *.out *Notes.bib; ); done
	rm -fr figures.pdf Manuscript/paper.pdf ../dist/gh-pages/spEnergiesQD/Manuscript/paper.pdf ../dist/gh-pages/spEnergiesQD/figures.pdf

deploy: ../dist/gh-pages/.git/config all
	cd ../dist/gh-pages && \
	git add -A && \
	git commit --amend -q -m Autogenerated && \
	git push -f origin master:gh-pages

purge:
	rm -fr Datafiles/.cache

../dist/gh-pages/.git/config:
	mkdir -p ../dist/gh-pages
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` && \
	cd ../dist/gh-pages && \
	git init && \
	git config user.name Bot && \
	git config user.email "<>" && \
	git commit -m _ --allow-empty && \
	git remote add origin "$$url"

../dist/gh-pages/spEnergiesQD/figures.pdf: figures.pdf
	mkdir -p $(@D)
	cp figures.pdf $@

../dist/gh-pages/spEnergiesQD/Manuscript/paper.pdf: Manuscript/paper.pdf
	mkdir -p $(@D)
	cp Manuscript/paper.pdf $@

.SUFFIXES: .dep .md .md_dep .pdf .svg .tex

.md.md_dep:
	./gen-deps $< $@

.md.tex:
	pandoc -s -V fontsize=12pt -o $@ $<

.svg.pdf:
	inkscape --without-gui --export-pdf=$@ $<

.tex.dep:
	./gen-deps $< $@

.tex.pdf:
	./mklatex $*

-include figures.md_dep Manuscript/paper.dep

.SECONDARY:
