#!/bin/sh
# shut up LaTeX
set -eu
rm -f "$1.log"
dir=`dirname "$1"`
base=`basename "$1"`
cd "${dir}"     # LaTeX would otherwise dump things into the current directory
latexmk -g -pdf -silent -interaction=nonstopmode "${base}" || {
    e=$?
    grep --color -A8 '^!.*' "${base}".log
    exit $e
}
