#!/bin/sh
dir=`dirname "$1"` &&
base=`basename "$1"` &&
rm -f "$1.log" &&

# workaround: LaTeX dumps its trash into the *current* directory rather than
# the directory of the input file
cd "${dir}" &&

# shut up LaTeX
latexmk -g -pdf -silent -halt-on-error -interaction=nonstopmode "${base}" || {
    e=$? &&
    if [ -f "${base}.log" ]; then
        grep -A 8 '^!.*' "${base}.log"
    fi &&
    exit $e
}
